import { Region, Puzzle } from '@/engine';
import pnw from './regions/pnw.json';
import appalachia from './regions/appalachia.json';
import greatlakes from './regions/greatlakes.json';
import southwest from './regions/southwest.json';
import atlantic from './regions/atlantic.json';

// The full catalog: 5 regions x 100 puzzles, generated by `npm run generate-puzzles` from
// content/generator/ and content/<id>/region.gen.json (the editable source). JSON widens the
// engine's literal union types (tier, voice) to string, so cast through unknown.
const asRegion = (json: unknown): Region => json as unknown as Region;

export const sampleRegions: Region[] = [pnw, appalachia, greatlakes, southwest, atlantic].map(asRegion);

export function getSampleRegion(id: string): Region | undefined {
  return sampleRegions.find((r) => r.id === id);
}

export function getPuzzleById(id: string): Puzzle | undefined {
  for (const region of sampleRegions) {
    const found = region.puzzles.find((p) => p.id === id);
    if (found) return found;
  }
  return undefined;
}
