import { Region, Puzzle } from '@/engine';
import { colors } from '@/theme';
import { buildPuzzle } from './buildPuzzle';
import { samplePuzzles } from './samplePuzzles';
import superiorJson from './regions/superior.json';

// Generated by `npm run import-region` from content/superior/ (placeholder art).
// The JSON is a fully-derived Region; cast through unknown because JSON widens the
// engine's literal union types (difficulty tier, voice style) to plain strings.
const superiorRegion = superiorJson as unknown as Region;

// A second region's puzzle (locked/paid) to exercise lock + purchase flows.
const appalachiaPuzzles = [
  buildPuzzle({
    id: 'appalachia-001',
    name: 'The Hollow',
    subtitle: 'Unidentified · Field Test',
    grid: [
      [0, 1, 1, 1, 0],
      [1, 1, 0, 1, 1],
      [1, 0, 0, 0, 1],
      [1, 1, 0, 1, 1],
      [0, 1, 1, 1, 0],
    ],
    entry: {
      title: 'THE HOLLOW · Case 101',
      body: 'Something circled the hollow three times and did not come back a fourth. The dogs would not follow.',
      voiceStyle: 'firstPerson',
      yearReported: 1991,
      witnessCredibility: 'medium',
    },
    metadata: { regionId: 'appalachia', order: 1, isCapstone: false },
  }),
];

export const sampleRegions: Region[] = [
  {
    id: 'pnw',
    name: 'The Pacific Northwest',
    tagline: 'Where the trees watch',
    tint: colors.region.pnw,
    puzzles: samplePuzzles,
    totalPuzzles: samplePuzzles.length,
    isFree: true,
  },
  {
    id: 'appalachia',
    name: 'Appalachia',
    tagline: 'The old roads remember',
    tint: colors.region.appalachia,
    puzzles: appalachiaPuzzles,
    totalPuzzles: appalachiaPuzzles.length,
    isFree: false,
    iapProductId: 'region.appalachia',
  },
  superiorRegion,
];

export function getSampleRegion(id: string): Region | undefined {
  return sampleRegions.find((r) => r.id === id);
}

export function getPuzzleById(id: string): Puzzle | undefined {
  for (const region of sampleRegions) {
    const found = region.puzzles.find((p) => p.id === id);
    if (found) return found;
  }
  return undefined;
}
