import type { ArtEntry } from './types';

/**
 * Shared evidence/item icon pool. Fills the Easy tier of every region.
 * Each grid is hand-authored to: be already trimmed (no blank border), have
 * max dimension <= 8, be line-solvable ("unique"), and score the Easy
 * difficulty tier. See content/art/__tests__/icons.test.ts for the gate.
 */
export const ICONS: ArtEntry[] = [
  // --- evidence icons ---------------------------------------------------
  {
    key: 'footprint',
    kind: 'icon',
    label: 'Cast Footprint',
    grid: [
      '.#.#.',
      '.###.',
      '#####',
      '.###.',
      '..#..',
    ],
  },
  {
    key: 'eye',
    kind: 'icon',
    label: 'Eyeshine',
    grid: [
      '..###..',
      '.#####.',
      '##.#.##',
      '.#####.',
      '..###..',
    ],
  },
  {
    key: 'feather',
    kind: 'icon',
    label: 'Molted Feather',
    grid: [
      '..#..',
      '#####',
      '..#..',
      '.###.',
      '..#..',
      '.###.',
      '..#..',
      '..#..',
    ],
  },
  {
    key: 'claw-rake',
    kind: 'icon',
    label: 'Claw Rake',
    grid: [
      '#####',
      '#.#.#',
      '#.#.#',
      '..#..',
      '..#..',
    ],
  },
  {
    key: 'fang',
    kind: 'icon',
    label: 'Fang Mark',
    grid: [
      '#####',
      '.###.',
      '.###.',
      '..#..',
      '..#..',
    ],
  },
  {
    key: 'fur-tuft',
    kind: 'icon',
    label: 'Tuft of Fur',
    grid: [
      '#.#.#',
      '#.#.#',
      '#####',
      '.###.',
      '..#..',
    ],
  },
  {
    key: 'track-pair',
    kind: 'icon',
    label: 'Track Pair',
    grid: [
      '##...##',
      '##...##',
      '.#####.',
      '##...##',
      '##...##',
    ],
  },
  {
    key: 'handprint',
    kind: 'icon',
    label: 'Handprint',
    grid: [
      '#.#.#.#',
      '#######',
      '#######',
      '#######',
      '.#####.',
      '..###..',
    ],
  },
  {
    key: 'paw',
    kind: 'icon',
    label: 'Paw Print',
    grid: [
      '#.#.#.#',
      '.......',
      '.#####.',
      '#######',
      '#######',
      '.#####.',
    ],
  },
  {
    key: 'horn',
    kind: 'icon',
    label: 'Curved Horn',
    grid: [
      '#####',
      '.###.',
      '.##..',
      '.##..',
      '..#..',
    ],
  },
  {
    key: 'scale',
    kind: 'icon',
    label: 'Shed Scale',
    grid: [
      '..#..',
      '.###.',
      '#####',
      '.###.',
      '..#..',
    ],
  },
  {
    key: 'bite-mark',
    kind: 'icon',
    label: 'Bite Mark',
    grid: [
      '..###..',
      '.#####.',
      '#####..',
      '####...',
      '#######',
      '.#####.',
      '..###..',
    ],
  },

  // --- item icons ---------------------------------------------------------
  {
    key: 'saucer',
    kind: 'item',
    label: 'The Object',
    grid: [
      '...#...',
      '..###..',
      '.#####.',
      '#######',
      '.#.#.#.',
    ],
  },
  {
    key: 'jar',
    kind: 'item',
    label: 'Specimen Jar',
    grid: [
      '.####.',
      '#....#',
      '#....#',
      '#....#',
      '#....#',
      '######',
    ],
  },
  {
    key: 'lantern',
    kind: 'item',
    label: 'Field Lantern',
    grid: [
      '..#..',
      '.###.',
      '#####',
      '#.#.#',
      '#####',
      '.###.',
    ],
  },
  {
    key: 'tent',
    kind: 'item',
    label: 'Camp Tent',
    grid: [
      '...#...',
      '..###..',
      '.#####.',
      '#######',
      '##.#.##',
    ],
  },
  {
    key: 'camera',
    kind: 'item',
    label: 'Trail Camera',
    grid: [
      '..##...',
      '#######',
      '#.....#',
      '#.###.#',
      '#.....#',
      '#######',
    ],
  },
  {
    key: 'egg',
    kind: 'item',
    label: 'Mystery Egg',
    grid: [
      '..##..',
      '.####.',
      '######',
      '######',
      '######',
      '.####.',
    ],
  },
  {
    key: 'boot',
    kind: 'item',
    label: 'Muddy Boot',
    grid: [
      '##....',
      '##....',
      '##....',
      '##....',
      '######',
    ],
  },
  {
    key: 'film-strip',
    kind: 'item',
    label: 'Film Strip',
    grid: [
      '#.#.#.#',
      '#######',
      '#.....#',
      '#.....#',
      '#######',
      '#.#.#.#',
    ],
  },
  {
    key: 'radio-tower',
    kind: 'item',
    label: 'Radio Tower',
    grid: [
      '..#..',
      '.###.',
      '.#.#.',
      '#...#',
      '#...#',
      '#####',
    ],
  },
  {
    key: 'tag',
    kind: 'item',
    label: 'Evidence Tag',
    grid: [
      '.###..',
      '.#.#..',
      '.###..',
      '######',
      '######',
      '######',
      '..##..',
    ],
  },
  {
    key: 'compass',
    kind: 'item',
    label: 'Compass Rose',
    grid: [
      '..#..',
      '.###.',
      '#.#.#',
      '.###.',
      '..#..',
    ],
  },
  {
    key: 'magnifier',
    kind: 'item',
    label: 'Magnifying Glass',
    grid: [
      '.###.',
      '#####',
      '#####',
      '.###.',
      '...#.',
      '....#',
    ],
  },
];
